project_name: nats-top

release:
  draft: true
  github:
    owner: nats-io
    name: nats-top

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - mips64le
      - s390x
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: freebsd
        goarch: 386

checksum:
  name_template: 'checksums.txt'

nfpms:
  - formats:
      - deb
      - rpm
    file_name_template: >-
        {{ .ProjectName }}-v{{ .Version }}-
        {{- .Os }}-
        {{- if eq .Arch "amd64" }}x86_64
        {{- else if eq .Arch "386" }}i386
        {{- else }}{{ .Arch }}{{ end }}
        {{- if .Arm }}v{{ .Arm }}{{ end }}
    bindir: /usr/local/bin
    description: "Top(1) style utility for NATS"
    vendor: nats.io
    homepage: https://nats.io
    license: MIT
    maintainer: Synadia <info@synadia.com>
