language: go

go:
  - 1.19
  - 1.20

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
  allow_failures:
    - go: tip

script:
  - go fmt ./...
  - go test -v -race ./util/

after_success:
  - |
    case "$TRAVIS_GO_VERSION" in
      (1.19|1.19.*)
        if [[ "$BUILD_GOOS" == "linux" ]] && [[ -n "$TRAVIS_TAG" ]]; then
          ./scripts/cross_compile.sh
          ghr --username wallyqs --token $GITHUB_TOKEN --replace --debug "$TRAVIS_TAG" pkg/
        fi
        ;;
    esac
